### PR TITLE
lower react version

### PR DESCRIPTION
**Pull request by untzag**
material-ui 4.11.0 is incompatible with react 17

or I'm missing something :thinking:

### CODE REVIEW

**Comment by untzag** [comment]
also we should not track package-lock

**Comment by tyler314** [comment]
Why do we need a lower version of react? And we may need to commit the package-lock in the future, but I'm not quite sure. We can always remove it from gitignore if we need to.

**Comment by untzag** [comment]
https://github.com/mui-org/material-ui/issues/23306

**Comment by tyler314** [comment]
That is with typescript, does that apply to this project?

**Comment by untzag** [comment]
Yes, I believe it is. Try running Try material-ui 4.11.0 with react 17 in docker and you should get an incompatibility error.

**Comment by untzag** [comment]
It might work on your host machine because you've turned on `legacy-peer-deps` mode for npm... just an idea :thinking:

**Review by tyler314 — APPROVED** [review]
LGTM

**Pull request merged**
